global using Serilog;
global using BettingGame;
global using BettingGame.Common;
global using BettingGame.Abstractions;
global using BettingGame.Commands;
global using BettingGame.Constants;
global using BettingGame.Data.Models;
global using BettingGame.Exceptions;
global using System.Globalization;
