version: '3.9'

services:
  betting.game:
    image: ${DOCKER_REGISTRY-}betting.game
    build:
      context: .
      dockerfile: BettingGame/BettingGame/Dockerfile
    stdin_open: true
    tty: true
    profiles:
      - interactive